// Generated by scripts/generate-registry.mjs. Do not edit manually.

import shorthand0 from "./-webkit-border-before.js";
import shorthand1 from "./-webkit-mask-box-image.js";
import shorthand2 from "./-webkit-text-stroke.js";
import shorthand3 from "./all.js";
import shorthand4 from "./animation-range.js";
import shorthand5 from "./animation.js";
import shorthand6 from "./background.js";
import shorthand7 from "./border-block-end.js";
import shorthand8 from "./border-block-start.js";
import shorthand9 from "./border-block.js";
import shorthand10 from "./border-bottom.js";
import shorthand11 from "./border-color.js";
import shorthand12 from "./border-image.js";
import shorthand13 from "./border-inline-end.js";
import shorthand14 from "./border-inline-start.js";
import shorthand15 from "./border-inline.js";
import shorthand16 from "./border-left.js";
import shorthand17 from "./border-radius.js";
import shorthand18 from "./border-right.js";
import shorthand19 from "./border-style.js";
import shorthand20 from "./border-top.js";
import shorthand21 from "./border-width.js";
import shorthand22 from "./border.js";
import shorthand23 from "./column-rule.js";
import shorthand24 from "./columns.js";
import shorthand25 from "./contain-intrinsic-size.js";
import shorthand26 from "./container.js";
import shorthand27 from "./flex-flow.js";
import shorthand28 from "./flex.js";
import shorthand29 from "./font-synthesis.js";
import shorthand30 from "./font-variant.js";
import shorthand31 from "./font.js";
import shorthand32 from "./gap.js";
import shorthand33 from "./grid-area.js";
import shorthand34 from "./grid-column.js";
import shorthand35 from "./grid-row.js";
import shorthand36 from "./grid-template.js";
import shorthand37 from "./grid.js";
import shorthand38 from "./inset-block.js";
import shorthand39 from "./inset-inline.js";
import shorthand40 from "./inset.js";
import shorthand41 from "./list-style.js";
import shorthand42 from "./margin-block.js";
import shorthand43 from "./margin-inline.js";
import shorthand44 from "./margin.js";
import shorthand45 from "./mask-border.js";
import shorthand46 from "./mask.js";
import shorthand47 from "./offset.js";
import shorthand48 from "./outline.js";
import shorthand49 from "./overflow.js";
import shorthand50 from "./overscroll-behavior.js";
import shorthand51 from "./padding-block.js";
import shorthand52 from "./padding-inline.js";
import shorthand53 from "./padding.js";
import shorthand54 from "./place-content.js";
import shorthand55 from "./place-items.js";
import shorthand56 from "./place-self.js";
import shorthand57 from "./position-try.js";
import shorthand58 from "./scroll-margin-block.js";
import shorthand59 from "./scroll-margin-inline.js";
import shorthand60 from "./scroll-margin.js";
import shorthand61 from "./scroll-padding-block.js";
import shorthand62 from "./scroll-padding-inline.js";
import shorthand63 from "./scroll-padding.js";
import shorthand64 from "./scroll-timeline.js";
import shorthand65 from "./text-box.js";
import shorthand66 from "./text-decoration.js";
import shorthand67 from "./text-emphasis.js";
import shorthand68 from "./text-wrap.js";
import shorthand69 from "./transition.js";
import shorthand70 from "./view-timeline.js";

export const SHORTHANDS = [
  shorthand0,
  shorthand1,
  shorthand2,
  shorthand3,
  shorthand4,
  shorthand5,
  shorthand6,
  shorthand7,
  shorthand8,
  shorthand9,
  shorthand10,
  shorthand11,
  shorthand12,
  shorthand13,
  shorthand14,
  shorthand15,
  shorthand16,
  shorthand17,
  shorthand18,
  shorthand19,
  shorthand20,
  shorthand21,
  shorthand22,
  shorthand23,
  shorthand24,
  shorthand25,
  shorthand26,
  shorthand27,
  shorthand28,
  shorthand29,
  shorthand30,
  shorthand31,
  shorthand32,
  shorthand33,
  shorthand34,
  shorthand35,
  shorthand36,
  shorthand37,
  shorthand38,
  shorthand39,
  shorthand40,
  shorthand41,
  shorthand42,
  shorthand43,
  shorthand44,
  shorthand45,
  shorthand46,
  shorthand47,
  shorthand48,
  shorthand49,
  shorthand50,
  shorthand51,
  shorthand52,
  shorthand53,
  shorthand54,
  shorthand55,
  shorthand56,
  shorthand57,
  shorthand58,
  shorthand59,
  shorthand60,
  shorthand61,
  shorthand62,
  shorthand63,
  shorthand64,
  shorthand65,
  shorthand66,
  shorthand67,
  shorthand68,
  shorthand69,
  shorthand70,
] as const;
