import { generate, List, parse, walk } from "css-tree";
import {
  collapseToShorthand,
  expandShorthand,
  type CssomOptions,
  type DeclarationMap,
} from "./core.js";
import { SHORTHAND_DEFINITIONS } from "./registry.js";

export type TransformMode = "expand" | "collapse";

export interface TransformCssOptions extends CssomOptions {
  mode: TransformMode;
}

type EffectiveDeclaration = {
  value: string;
  important: boolean;
};

function makeDeclaration(property: string, value: string, important = false): any {
  return parse(`${property}:${value}${important ? "!important" : ""}`, {
    context: "declaration",
  });
}

function declarationValue(node: any): string {
  return generate(node.value).trim();
}

function normalizeProperty(property: string): string {
  return property.trim().toLowerCase();
}

function expandBlock(children: any[], options?: CssomOptions): any[] {
  const output: any[] = [];
  for (const child of children) {
    if (child.type !== "Declaration") {
      output.push(child);
      continue;
    }
    const expanded = expandShorthand(child.property, declarationValue(child), options);
    if (!expanded) {
      output.push(child);
      continue;
    }
    for (const [property, value] of Object.entries(expanded)) {
      output.push(makeDeclaration(property, value, Boolean(child.important)));
    }
  }
  return output;
}

const COLLAPSE_CANDIDATES = Object.entries(SHORTHAND_DEFINITIONS)
  .filter(([, definition]) => definition.longhands.length > 0)
  .sort(([, a], [, b]) => b.longhands.length - a.longhands.length);

function declarationWouldApply(
  current: EffectiveDeclaration | undefined,
  important: boolean,
): boolean {
  return important || !current?.important;
}

/**
 * Computed-style/export CSS commonly contains a shorthand followed by every one of
 * its resolved longhands. Those longhands are semantically redundant but used to
 * prevent the collapse pass from producing useful output.
 *
 * Track the effective value of declarations within a block and discard declarations
 * that do not change it. Unsupported/complex shorthands are never removed themselves,
 * but when CSSOM can expand them their following longhands can still be recognized as
 * redundant.
 */
function removeRedundantDeclarations(children: any[], options?: CssomOptions): any[] {
  const output: any[] = [];
  const effective = new Map<string, EffectiveDeclaration>();

  for (const child of children) {
    if (child.type !== "Declaration") {
      output.push(child);
      continue;
    }

    const property = normalizeProperty(child.property);
    const value = declarationValue(child);
    const important = Boolean(child.important);
    const definition = SHORTHAND_DEFINITIONS[property];

    if (definition) {
      const expanded = expandShorthand(property, value, options);

      if (expanded) {
        const entries = Object.entries(expanded);
        const changesEffectiveValue = entries.some(([longhand, longhandValue]) => {
          const current = effective.get(longhand);
          if (!declarationWouldApply(current, important)) return false;
          return !current || current.value !== longhandValue || current.important !== important;
        });

        // Pure shorthands have no hidden reset semantics beyond their registered
        // longhands, so an identical restatement can be dropped safely. Keep complex
        // CSSOM-backed shorthands themselves because they may reset additional state.
        const redundantPureShorthand =
          definition.strategy !== "unsupported" && !changesEffectiveValue;

        if (!redundantPureShorthand) output.push(child);

        for (const [longhand, longhandValue] of entries) {
          const current = effective.get(longhand);
          if (!declarationWouldApply(current, important)) continue;
          effective.set(longhand, { value: longhandValue, important });
        }
        continue;
      }

      // We know which longhands the shorthand affects, but not their resulting values.
      // Invalidate only values this declaration can actually override.
      for (const longhand of definition.longhands) {
        const current = effective.get(longhand);
        if (declarationWouldApply(current, important)) effective.delete(longhand);
      }
      output.push(child);
      continue;
    }

    const current = effective.get(property);

    // A non-important declaration cannot override an existing !important value.
    if (!declarationWouldApply(current, important)) continue;

    // Exact repeated declarations are redundant, including longhands generated by
    // getComputedStyle()-style exporters after an equivalent shorthand.
    if (current && current.value === value && current.important === important) continue;

    output.push(child);
    effective.set(property, { value, important });
  }

  return output;
}

function overlapsCandidate(property: string, expected: Set<string>): boolean {
  const definition = SHORTHAND_DEFINITIONS[property];
  return Boolean(definition?.longhands.some((longhand) => expected.has(longhand)));
}

/**
 * Find a collapsible shorthand starting at `index`. Longhands do not need to be
 * contiguous; unrelated declarations and comments may appear between them. Any
 * overlapping shorthand or duplicate constituent stops the candidate so cascade
 * semantics are not silently reordered.
 */
function tryCollapseAt(
  children: any[],
  index: number,
  consumed: Set<number>,
  options?: CssomOptions,
): { node: any; indices: number[] } | null {
  const first = children[index];
  if (!first || first.type !== "Declaration" || consumed.has(index)) return null;

  const firstProperty = normalizeProperty(first.property);

  for (const [shorthand, definition] of COLLAPSE_CANDIDATES) {
    if (!definition.longhands.includes(firstProperty)) continue;

    const expected = new Set(definition.longhands);
    const matches = new Map<string, { node: any; index: number }>();
    const important = Boolean(first.important);
    let blocked = false;

    for (let cursor = index; cursor < children.length; cursor += 1) {
      if (consumed.has(cursor)) continue;
      const node = children[cursor];
      if (node.type !== "Declaration") continue;

      const property = normalizeProperty(node.property);

      if (expected.has(property)) {
        if (Boolean(node.important) !== important || matches.has(property)) {
          blocked = true;
          break;
        }
        matches.set(property, { node, index: cursor });
        if (matches.size === expected.size) break;
        continue;
      }

      if (overlapsCandidate(property, expected)) {
        blocked = true;
        break;
      }
    }

    if (blocked || matches.size !== expected.size) continue;

    const declarations: DeclarationMap = {};
    for (const [property, match] of matches) {
      declarations[property] = declarationValue(match.node);
    }

    const collapsed = collapseToShorthand(shorthand, declarations, options);
    if (!collapsed) continue;

    return {
      node: makeDeclaration(collapsed.property, collapsed.value, important),
      indices: [...matches.values()].map((match) => match.index),
    };
  }

  return null;
}

/** Remove earlier declarations fully shadowed by a later declaration of the same property. */
function removeShadowedSameProperty(children: any[]): any[] {
  const keep = children.map(() => true);
  const later = new Map<string, { important: boolean }>();

  for (let index = children.length - 1; index >= 0; index -= 1) {
    const node = children[index];
    if (node.type !== "Declaration") continue;

    const property = normalizeProperty(node.property);
    const important = Boolean(node.important);
    const laterDeclaration = later.get(property);

    if (laterDeclaration && (laterDeclaration.important || !important)) {
      keep[index] = false;
      continue;
    }

    if (!laterDeclaration || important) {
      later.set(property, { important });
    }
  }

  return children.filter((_, index) => keep[index]);
}

function collapseBlock(children: any[], options?: CssomOptions): any[] {
  const normalized = removeRedundantDeclarations(children, options);
  const output: any[] = [];
  const consumed = new Set<number>();

  for (let index = 0; index < normalized.length; index += 1) {
    if (consumed.has(index)) continue;

    const collapsed = tryCollapseAt(normalized, index, consumed, options);
    if (!collapsed) {
      output.push(normalized[index]);
      continue;
    }

    output.push(collapsed.node);
    for (const matchedIndex of collapsed.indices) consumed.add(matchedIndex);
  }

  return removeShadowedSameProperty(output);
}

function replaceChildren(block: any, children: any[]): void {
  const list = new List();
  for (const child of children) list.appendData(child);
  block.children = list;
}

export function transformCss(css: string, options: TransformCssOptions): string {
  const ast: any = parse(css, { context: "stylesheet" });

  walk(ast, {
    visit: "Block",
    enter(block: any) {
      const children = block.children.toArray();
      const transformed = options.mode === "expand"
        ? expandBlock(children, options)
        : collapseBlock(children, options);
      replaceChildren(block, transformed);
    },
  });

  return generate(ast);
}

export function expandCss(css: string, options?: CssomOptions): string {
  return transformCss(css, { ...options, mode: "expand" });
}

export function collapseCss(css: string, options?: CssomOptions): string {
  return transformCss(css, { ...options, mode: "collapse" });
}

function transformDeclarationBlock(
  declarations: string,
  mode: TransformMode,
  options?: CssomOptions,
): string {
  const selector = ".__css_expand_collapse__";
  const output = transformCss(`${selector}{${declarations}}`, { ...options, mode });
  const open = output.indexOf("{");
  const close = output.lastIndexOf("}");
  return open === -1 || close === -1 ? output : output.slice(open + 1, close);
}

export function expandDeclarations(declarations: string, options?: CssomOptions): string {
  return transformDeclarationBlock(declarations, "expand", options);
}

export function collapseDeclarations(declarations: string, options?: CssomOptions): string {
  return transformDeclarationBlock(declarations, "collapse", options);
}
